/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package be.bowling;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class GameTest {
    private Game game;

    @BeforeEach
    void setUp() {
        game = new Game();
    }

    @Test
    void newGameHasZeroScore() {
        assertEquals(0, game.score());
    }

    @Test
    void roll1ResultsInScore1() {
        game.roll(1);

        assertEquals(1, game.score());
    }

    @Test
    void secondRollRetultsInChangedScore() {
        game.roll(1);
        game.roll(2);

        assertEquals(3, game.score());
    }

    @Test
    void rollCanNotbeMoreThanMax() {
        game.roll(6);

        assertThrowsExactly(IllegalPinException.class, () -> game.roll(7) );
    }

    @Test
    void threeRollsShouldWork() {
        game.roll(3);
        game.roll(6);
        game.roll(4);

        assertEquals(13, game.score());
    }

    @Test
    void shouldReturn10() {
        game.roll(7);
        game.roll(3);

        assertEquals(10, game.score());
    }

    @Test
    @Disabled
    void spareShouldGiveBonusPoints() {
        game.roll(7);
        game.roll(3);
        game.roll(5);

        assertEquals(20, game.score());
    }
}
